load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

go_library(
    name = "go_default_library",
    srcs = [
        "cost.go",
        "default_strategy.go",
        "estimator.go",
        "model.go",
        "strategy.go",
        "tracker.go",
    ],
    importpath = "cel.dev/cel-go/common/cost",
    deps = [
        "//common/ast:go_default_library",
        "//common/operators:go_default_library",
        "//common/overloads:go_default_library",
        "//common/types:go_default_library",
        "//common/types/ref:go_default_library",
        "//common/types/traits:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    size = "small",
    srcs = [
        "cost_test.go",
        "default_strategy_test.go",
        "estimator_test.go",
        "model_test.go",
        "tracker_test.go",
    ],
    embed = [
        ":go_default_library",
    ],
    deps = [
        "//checker:go_default_library",
        "//common:go_default_library",
        "//common/ast:go_default_library",
        "//common/containers:go_default_library",
        "//common/decls:go_default_library",
        "//common/operators:go_default_library",
        "//common/overloads:go_default_library",
        "//common/stdlib:go_default_library",
        "//common/types:go_default_library",
        "//common/types/ref:go_default_library",
        "//interpreter:go_default_library",
        "//parser:go_default_library",
        "//test/proto3pb:go_default_library",
    ],
)
